<a href="https://colab.research.google.com/github/igsneves/Disciplina-de-Intelig-ncia-Artificial/blob/main/ExerciciosNumPy_IGOR_DA_SILVA_NEVES_Turma_6B_Noturno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercicio 1

In [ ]:
import numpy as np

array = np.random.randint(10, 101, 50)

print(array)

[49 43 59 19 32 93 25 90 68 34 35 67 26 93 71 43 46 63 24 60 44 55 59 40
 75 54 20 38 82 76 86 10 81 42 63 77 15 21 99 17 61 72 50 23 53 38 18 46
 66 93]


Exercicio 2

In [ ]:
import numpy as np

array = np.arange(1,17);

matriz = array.reshape(4,4);

print(matriz[3,:]);

[13 14 15 16]


Exercicio 3

In [ ]:
import numpy as np

array = np.zeros(15);
array[4:10] = 1
print(array)

[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


Exercicio 4

In [ ]:
import numpy as rp
from statistics import mode

array = rp.random.randint(1,101,100);
mediana = np.median(array);
moda = mode(array);

print(mediana)
print(moda)

48.0
8


Exercicio 5

In [ ]:
import numpy as rp

array = rp.random.randint(1,101,20);
array [array % 3 == 0] = -3
print(array)

[ -3  -3  11  -3 100  10  58  -3  61  26  58  88  -3  -3  -3  74  -3  -3
  -3  59]


Exercicio 6

In [ ]:
import numpy as rp

matriz = rp.random.rand(5,5)

somacolunas = rp.sum(matriz, axis=0)

print(matriz)
print(somacolunas)

[[0.50247757 0.86022873 0.61335344 0.81679912 0.24162472]
 [0.44132535 0.62816446 0.51311654 0.00309333 0.18776591]
 [0.28439534 0.6101488  0.94212487 0.50095852 0.01974223]
 [0.68062089 0.70112794 0.73908936 0.06699297 0.93810779]
 [0.30412802 0.99313147 0.58775844 0.74855697 0.32766232]]
13.25249509360852


Exercicio 7

In [ ]:
import numpy as rp

array1 = rp.random.rand(20);
array2 = rp.random.rand(20);

correlacao1 = rp.corrcoef(array1,array2);
correlacao = correlacao1[0,1];

print(correlacao);

-0.32642823641408897


Exercicio 8

In [ ]:
import numpy as np

matriz = np.random.randint(1, 101, (3, 3))
elevado = matriz ** 2

print(matriz)
print(elevado)

Exercicio 9

In [ ]:
import numpy as np

array = np.random.randint(1,20,10);
min = np.min(array);
max = np.max(array);

normalizado = (array - min) / (max - min)

print(normalizado)


[0.         0.6        0.2        0.13333333 0.         0.86666667
 1.         0.93333333 0.13333333 0.8       ]


Exercicio 10

In [ ]:
import numpy as np

matriz = np.eye(6)
matriz[np.diag_indices(6)] = [1, 2, 3, 4, 5, 6]

print(matriz)

[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]


Exercicio 11

In [ ]:
import numpy as np

array = np.random.randint(1,101,100);

mais_repetido = np.bincount(array).argmax()

print(mais_repetido)

13


Exercicio 12

In [ ]:
import numpy as np

matriz = np.random.randint(1, 10, (4, 4))

np.fill_diagonal(matriz, 7)

print(matriz)

[[7 9 8 3]
 [1 7 6 9]
 [8 9 7 5]
 [2 4 8 7]]


Exercicio 13

In [ ]:
import numpy as np

array = np.arange(2, 21, 2)

soma_cumulativa = np.cumsum(array)

print("Array:", array)
print("Soma cumulativa:", soma_cumulativa)

Array: [ 2  4  6  8 10 12 14 16 18 20]
Soma cumulativa: [  2   6  12  20  30  42  56  72  90 110]


Exercicio 14

In [ ]:
import numpy as np

array1 = np.random.randint(1,11,10);
array2 = np.random.randint(1,11,10);

diferenca = array1 - array2;

media = np.mean(diferenca);

print("Array 1:", array1)
print("Array 2:", array2)
print("Diferença:", diferenca)
print("Média das diferenças:", media)

Array 1: [ 1  7  9  9  9  5  8  8 10  6]
Array 2: [ 9  9  2  7  5  2  3  5 10  5]
Diferença: [-8 -2  7  2  4  3  5  3  0  1]
Média das diferenças: 1.5


Exercicio 15

In [ ]:
import numpy as np

array = np.random.randint(1, 101,10);

array[array > 50] = 50;

print(array)

[ 7 12 50 50 50 50  3 31  5 10]


Exercicio 16

In [ ]:
import numpy as rp

array = rp.arange(1, 13)

matriz = array.reshape(3, 4)

print("Array:")
print(array)

print("Matriz:")
print(matriz)

Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Matriz:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Exercicio 17

In [ ]:
import numpy as rp

matriz = rp.random.randint(1, 10, (4, 4))

linhas, colunas = rp.indices((4, 4))

resultado = matriz * (linhas + colunas)

print("Matriz:")
print(matriz)

print("Resultado:")
print(resultado)

Matriz:
[[3 9 2 4]
 [2 3 2 1]
 [6 1 9 7]
 [7 4 4 4]]
Resultado:
[[ 0  9  4 12]
 [ 2  6  6  4]
 [12  3 36 35]
 [21 16 20 24]]


Exercicio 18

In [ ]:
import numpy as np

array = np.random.randint(1,101,10);

array[array % 5 == 0] = 0;

print(array)

[43  0 19  0 78 39  7  0 12  0]


Exercicio 19

In [ ]:
import numpy as np

array1 = np.random.randint(1, 10, 20)
array2 = np.random.randint(1, 10, 20)

produto_escalar = np.dot(array1, array2)

norma1 = np.linalg.norm(array1)
norma2 = np.linalg.norm(array2)

cos_theta = produto_escalar / (norma1 * norma2)

angulo = np.arccos(cos_theta)

print("Array 1:", array1)
print("Array 2:", array2)
print("Ângulo em radianos:", angulo)
print("Ângulo em graus:", np.degrees(angulo))

Array 1: [1 3 7 2 9 3 7 3 4 8 8 4 8 4 3 7 5 4 2 4]
Array 2: [1 3 3 2 2 5 8 9 3 3 3 2 6 9 3 3 1 4 5 4]
Ângulo em radianos: 0.6829407503064185
Ângulo em graus: 39.129622650055566


Exercicio 20

In [ ]:
import numpy as np

matriz = np.random.randint(1, 100, (4, 4))

minimo_linhas = np.min(matriz, axis=1)

print("Matriz:")
print(matriz)

print("Valor mínimo de cada linha:")
print(minimo_linhas)

Matriz:
[[ 4 16 60 61]
 [16 48  7 85]
 [71 95 95 13]
 [67 77 21 11]]
Valor mínimo de cada linha:
[ 4  7 13 11]
